In [6]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import csv

In [7]:

df=pd.read_csv("/content/Reviews.csv",on_bad_lines='skip', quoting=csv.QUOTE_NONE)

In [9]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1.0,1.0,5.0,1.303862e+09,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0.0,0.0,1.0,1.346976e+09,Not as Advertised,"""Product arrived labeled as Jumbo Salted Peanu..."
2,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3.0,3.0,2.0,1.307923e+09,Cough Medicine,If you are looking for the secret ingredient i...
3,9,B000E7L2R4,A1MZYO9TZK0BBI,R. James,1.0,1.0,5.0,1.322006e+09,Yay Barley,Right now I'm mostly just sprouting this so my...
4,10,B00171APVA,A21BT40VZCCYT4,Carol A. Reed,0.0,0.0,5.0,1.351210e+09,Healthy Dog Food,This is a very healthy dog food. Good for thei...

In [13]:
df = df.rename(columns={
    "Text": "Feedback",
    "ProductId": "Product_ID",
    "Score": "Rating"
})

In [16]:
df.head()

,Id,Product_ID,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Rating,Time,Summary,Feedback
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1.0,1.0,5.0,1.303862e+09,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0.0,0.0,1.0,1.346976e+09,Not as Advertised,"""Product arrived labeled as Jumbo Salted Peanu..."
2,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3.0,3.0,2.0,1.307923e+09,Cough Medicine,If you are looking for the secret ingredient i...
3,9,B000E7L2R4,A1MZYO9TZK0BBI,R. James,1.0,1.0,5.0,1.322006e+09,Yay Barley,Right now I'm mostly just sprouting this so my...
4,10,B00171APVA,A21BT40VZCCYT4,Carol A. Reed,0.0,0.0,5.0,1.351210e+09,Healthy Dog Food,This is a very healthy dog food. Good for thei...

In [14]:
sentences = df["Feedback"]

In [23]:
vectorizer = CountVectorizer()
# Fill missing values with empty strings to avoid ValueError
a=vectorizer.fit_transform(sentences.fillna(""))
vocabulary = vectorizer.vocabulary_

In [24]:
print(vocabulary)

{'have': 9790, 'bought': 2903, 'several': 18304, 'of': 14184, 'the': 20671, 'vitality': 22161, 'canned': 3528, 'dog': 6588, 'food': 8403, 'products': 16064, 'and': 1320, 'found': 8489, 'them': 20688, 'all': 1117, 'to': 20970, 'be': 2276, 'good': 9164, 'quality': 16392, 'product': 16059, 'looks': 12228, 'more': 13340, 'like': 12010, 'stew': 19623, 'than': 20648, 'processed': 16034, 'meat': 12821, 'it': 11019, 'smells': 18866, 'better': 2497, 'my': 13557, 'labrador': 11661, 'is': 10998, 'finicky': 8133, 'she': 18376, 'appreciates': 1509, 'this': 20774, 'most': 13374, 'arrived': 1605, 'labeled': 11646, 'as': 1641, 'jumbo': 11278, 'salted': 17764, 'peanuts': 14986, 'were': 22488, 'actually': 802, 'small': 18843, 'sized': 18699, 'unsalted': 21734, 'not': 13935, 'sure': 20115, 'if': 10438, 'was': 22333, 'an': 1307, 'error': 7406, 'or': 14374, 'vendor': 21997, 'intended': 10857, 'represent': 17128, 'you': 23032, 'are': 1553, 'looking': 12225, 'for': 8424, 'secret': 18131, 'ingredient': 10739, 'in': 10556, 'robitussin': 17494, 'believe': 2410, 'got': 9211, 'addition': 832, 'root': 17560, 'beer': 2358, 'extract': 7752, 'ordered': 14396, 'which': 22546, 'made': 12437, 'some': 19061, 'cherry': 4029, 'soda': 19002, 'flavor': 8235, 'very': 22046, 'medicinal': 12847, 'right': 17405, 'now': 13981, 'mostly': 13375, 'just': 11297, 'sprouting': 19411, 'so': 18983, 'cats': 3755, 'can': 3487, 'eat': 6977, 'grass': 9322, 'they': 20725, 'love': 12283, 'rotate': 17583, 'around': 1594, 'with': 22724, 'wheatgrass': 22525, 'rye': 17691, 'too': 21041, 'healthy': 9848, 'their': 20684, 'digestion': 6255, 'also': 1181, 'puppies': 16281, 'eats': 6987, 'her': 9944, 'required': 17151, 'amount': 1290, 'at': 1730, 'every': 7519, 'feeding': 7980, 'these': 20719, 'came': 3468, 'securely': 18140, 'packed': 14672, 'fresh': 8594, 'delicious': 5921, 'twizzlers': 21464, 'strawberry': 19761, 'guilty': 9541, 'pleasure': 15506, 'yummy': 23089, 'six': 18694, 'pounds': 15764, 'will': 22652, 'while': 22550, 'son': 19090, 'eating': 6985, 'watching': 22358, 'tv': 21434, 'movies': 13421, 'sweet': 20202, 'transfer': 21194, 'zip': 23140, 'lock': 12180, 'baggie': 2078, 'stay': 19570, 'take': 20338, 'time': 20902, 'am': 1218, 'satisfied': 17865, 'twizzler': 21463, 'purchase': 16296, 'shared': 18356, 'others': 14485, 'we': 22394, 'enjoyed': 7293, 'definitely': 5868, 'ordering': 14398, 'candy': 3510, 'delivered': 5947, 'fast': 7899, 'purchased': 16297, 'reasonable': 16661, 'price': 15953, 'home': 10111, 'bound': 2914, 'unable': 21533, 'get': 8941, 'store': 19714, 'perfect': 15114, 'me': 12800, 'remember': 17034, 'buying': 3352, 'kid': 11453, 'hasn': 9763, 'dropped': 6812, 'years': 22957, 'still': 19647, 'superb': 20043, 'won': 22760, 'disappointed': 6343, 'after': 955, 'weight': 22455, 'watchers': 22356, 'had': 9612, 'cut': 5554, 'back': 2049, 'but': 3324, 'craving': 5279, 'glad': 9029, 'amazon': 1244, 'carried': 3676, 'batteries': 2252, 'hard': 9721, 'finding': 8119, 'elsewhere': 7149, 'because': 2326, 'such': 19943, 'unique': 21663, 'size': 18698, 'need': 13683, 'garage': 8814, 'door': 6652, 'opener': 14338, 'br': 2960, 'great': 9359, 'deal': 5718, 'mccann': 12783, 'oatmeal': 14093, 'morning': 13354, 'by': 3357, 'from': 8645, 'able': 638, 'save': 17903, 'almost': 1157, '00': 0, 'per': 15103, 'box': 2936, 'tastes': 20435, 'really': 16655, 'steel': 19589, 'oats': 14095, 'find': 8118, 'don': 6627, 'cook': 5056, 'up': 21782, 'often': 14211, 'much': 13451, 'grocery': 9443, 'brands': 2986, 'convenient': 5021, 'anything': 1431, 'that': 20662, 'keeps': 11386, 'regularly': 16937, 'thing': 20751, 'apple': 1488, 'cinnamon': 4291, 'best': 2490, 'though': 20794, 'wouldn': 22844, 'follow': 8387, 'directions': 6316, 'on': 14278, 'package': 14665, 'since': 18643, 'always': 1215, 'comes': 4647, 'out': 14505, 'soupy': 19163, 'taste': 20426, 'could': 5167, 'thick': 20737, 'add': 816, 'milk': 13057, 'top': 21062, 'same': 17778, 'stuff': 19842, 'buy': 3348, 'big': 2538, 'stores': 19716, 'there': 20706, 'nothing': 13944, 'about': 650, 'carbs': 3624, 'sugars': 19977, 'your': 23043, 'money': 13300, 'something': 19072, 'least': 11847, 'has': 9758, 're': 16616, 'used': 21834, 'spicy': 19298, 'foods': 8409, 'down': 6702, 'here': 9956, 'south': 19175, 'texas': 20635, 'doubt': 6685, 'habanero': 9602, 'notch': 13937, 'two': 21466, 'awesome': 1878, 'before': 2368, 'halloween': 9644, 'indicated': 10632, 'enough': 7304, 'satisfy': 17868, 'trick': 21278, 'treaters': 21246, 'less': 11919, 'expensive': 7672, 'local': 12169, 'days': 5704, 'stale': 19500, 'any': 1416, 'bags': 2083, 'serves': 18274, 'well': 22476, 'source': 19165, 'electrolytes': 7107, 'during': 6896, 'long': 12209, 'run': 17655, 'bike': 2550, 'ride': 17387, 'tried': 21286, 'flavors': 8248, 'do': 6564, 'grapefruit': 9312, 'no': 13860, 'slight': 18786, 'carbonation': 3620, 'use': 21832, 'other': 14484, 'hammer': 9659, 'whole': 22592, 'line': 12054, 'works': 22813, 'preventing': 15942, 'cramping': 5253, 'middle': 13022, 'latter': 11772, 'stages': 19485, 'rides': 17389, 'pop': 15641, 'into': 10904, 'each': 6932, 'water': 22359, 'bottle': 2891, 'set': 18286, 'fine': 8122, 'goes': 9135, 'easy': 6976, 'those': 20792, 'us': 21823, 'low': 12298, 'carb': 3605, 'diet': 6211, 'little': 12127, 'tablets': 20301, 'ago': 995, 'started': 19542, 'cycling': 5570, 'again': 970, 'many': 12590, 'having': 9799, 'heart': 9859, 'arrhythmia': 1601, 'longer': 12211, 'high': 9999, 'heat': 9873, 'drinking': 6791, 'plain': 15444, 'did': 6196, 'research': 17175, 'thought': 20795, 'might': 13034, 'issue': 11014, 'gatorade': 8856, 'wasn': 22345, 'option': 14370, 'loaded': 12155, 'carbohydrates': 3615, 'looked': 12222, 'alternative': 1191, 'zero': 23121, 'sports': 19376, 'drinks': 6792, 'didn': 6199, 'help': 9926, 'what': 22513, 'one': 14284, 'day': 5699, 'ran': 16529, 'across': 784, 'shop': 18493, 'tube': 21374, 'voila': 22185, 'problem': 16020, 'solved': 19059, 've': 21951, 'friends': 8616, 'particular': 14861, 'whose': 22609, 'problems': 16022, 'leg': 11873, 'cramps': 5254, 'resolved': 17217, 'using': 21845, 'guys': 9592, 'superbly': 20044, 'formulated': 8463, 'simply': 18639, 'work': 22803, 'sooooo': 19105, 'deliscious': 5937, 'bad': 2069, 'ate': 1731, 'em': 7154, 'gained': 8790, 'pds': 14966, 'fault': 7926, 'okay': 14232, 'would': 22843, 'go': 9115, 'way': 22384, 'tea': 20475, 'brunch': 3167, 'artifial': 1629, 'returnable': 17299, 'wasted': 22349, '20': 200, 'bucks': 3200, 'been': 2355, 'purchasing': 16304, 'different': 6229, 'brand': 2983, 'similar': 18625, 'texture': 20638, 'agree': 1000, 'reviewer': 17330, 'regarding': 16907, 'summer': 20010, 'insulating': 10840, 'packaging': 14671, 'ice': 10401, 'packs': 14681, 'melt': 12890, 'warm': 22316, 'weather': 22414, 'chocolate': 4165, 'items': 11033, 'order': 14394, 'cold': 4568, 'last': 11753, 'peppermint': 15091, 'stick': 19631, 'fun': 8727, 'dad': 5587, 'christmas': 4234, 'he': 9819, 'remembered': 17035, 'when': 22533, 'girl': 9007, '30': 303, 'shepherd': 18413, 'collie': 4596, 'mix': 13193, 'ibs': 10398, 'our': 14501, 'vet': 22048, 'recommended': 16753, 'limited': 12041, 'helped': 9927, 'symptoms': 20265, 'likes': 12018, '10': 21, 'cheaper': 3958, 'free': 8564, 'shipping': 18465, 'natural': 13633, 'balance': 2103, 'dry': 6834, 'lamb': 11698, 'meal': 12804, 'brown': 3149, 'rice': 17364, 'recipe': 16720, 'wonders': 22773, 'jack': 11058, 'russell': 17672, 'awful': 1881, 'allergy': 1127, 'hope': 10166, 'allergic': 1124, 'normally': 13917, 'wet': 22501, 'seems': 18164, 'bichon': 2532, 'loves': 12291, 'stomach': 19686, 'want': 22303, 'see': 18148, 'difference': 6227, 'pet': 15199, 'standard': 19510, 'poodle': 15623, 'pomeranian': 15608, 'who': 22589, 'both': 2882, 'wonderful': 22766, 'switched': 20252, 'due': 6854, 'couple': 5192, 'times': 20909, 'end': 7233, 'going': 9141, 'ages': 984, 'dogs': 6599, 'year': 22955, 'old': 14241, 'puppy': 16282, 'soft': 19008, 'hardly': 9728, 'ever': 7509, 'sick': 18574, 'especially': 7430, 'prime': 15975, 'slightly': 18788, 'pleased': 15496, 'issues': 11016, 'past': 14890, 'someone': 19066, 'recommend': 16750, 'grain': 9258, 'possible': 15712, 'grains': 9261, 'switching': 20253, 'haven': 9794, 'helpful': 9930, 'kibble': 11444, 'larger': 11735, 'smaller': 18844, 'nice': 13804, 'pie': 15323, 'fact': 7797, 'slicing': 18780, 'dicing': 6192, 'prepare': 15878, 'loved': 12284, 'make': 12498, 'whenever': 22534, 'needed': 13684, 'creme': 5329, 'brulee': 3164, 'sprinkle': 19398, 'sugar': 19973, 'broil': 3126, 'look': 12221, 'amazing': 1239, 'guess': 9527, 'went': 22485, 'took': 21043, 'minutes': 13134, 'expecting': 7658, 'terms': 20595, 'company': 4703, 'reputation': 17145, 'excellent': 7579, 'delivery': 5951, 'doctor': 6574, 'office': 14198, 'available': 1835, 'com': 4622, 'drink': 6786, 'throughout': 20824, 'folks': 8386, 'coffee': 4532, 'helps': 9934, 'curb': 5511, 'mom': 13288, 'given': 9019, 'try': 21357, 'cat': 3727, '13': 86, 'cleo': 4387, 'trouble': 21326, 'keeping': 11385, 'loosing': 12249, 'stopped': 19706, 'doesn': 6585, 'justify': 11302, 'added': 818, 'aids': 1027, 'ok': 14231, 'sorry': 19140, 'gone': 9160, 'ya': 22933, 'know': 11554, 'mean': 12809, 'anyone': 1424, 'experiencing': 7681, 'lot': 12263, 'benifits': 2457, 'thrive': 20817, 'extremely': 7765, 'hair': 9626, 'ball': 2111, 'throw': 20827, 'ups': 21798, 'fur': 8745, 'fit': 8170, 'over': 14546, 'ships': 18469, 'suppliers': 20080, 'book': 2834, 'myself': 13565, 'liking': 12022, 'broth': 3142, 'noodles': 13899, 'usually': 21853, 'opposite': 14360, 'aren': 1558, 'bother': 2883, 'hot': 10215, 'allot': 1138, 'happens': 9708, 'favorites': 7944, 'getting': 8948, 'soon': 19101, 'cannot': 3538, 'australian': 1806, 'ginger': 8993, 'where': 22536, 'live': 12131, 'compares': 4711, 'favorably': 7937, 'cities': 4306, 'enjoy': 7290, 'without': 22733, 'traveling': 21232, 'give': 9016, 'people': 15074, 'snack': 18919, 'bite': 2616, 'easier': 6966, 'grab': 9234, 'pieces': 15325, 'rather': 16579, 'entire': 7336, 'licorice': 11970, 'only': 14298, 'complaint': 4742, 'broke': 3129, 'open': 14335, 'known': 11562, '50': 432, 'black': 2637, 'delicate': 5917, 'barely': 2169, 'salsas': 17760, 'away': 1874, 'variety': 21934, 'pack': 14663, 'come': 4641, 'worth': 22832, 'remind': 17039, 'treats': 21250, 'once': 14281, 'pumpkin': 16256, 'kind': 11477, 'bland': 2660, 'favorite': 7943, 'nature': 13636, 'finace': 8108, 'three': 20809, 'stars': 19539, 'chicken': 4076, 'fish': 8163, 'beef': 2347, 'pork': 15680, 'makes': 12502, 'plus': 15534, 'bulk': 3241, 'off': 14186, 'brother': 3143, 'jorge': 11227, 'cruise': 5412, 'decided': 5780, 'pretty': 15929, 'desserts': 6086, 'things': 20754, 'jello': 11140, 'definitentally': 5869, 'healthiest': 9843, 'salt': 17763, 'should': 18522, 'family': 7850, 'iodized': 10964, 'sea': 18087, 'raise': 16503, 'blood': 2720, 'pressure': 15918, 'regular': 16935, 'never': 13760, 'heard': 9856, 'safcol': 17721, 'tired': 20949, 'trying': 21361, 'typical': 21480, 'pouches': 15757, 'starkist': 19536, 'surprised': 20131, 'bit': 2614, 'seasoning': 18118, 'seriously': 18266, 'tasteless': 20432, 'tasting': 20443, '100': 22, 'calories': 3459, 'its': 11041, 'special': 19242, 'bar': 2152, 'cookie': 5065, 'season': 18113, 'combine': 4633, 'else': 7147, 'share': 18355, 'growing': 9478, 'lemon': 11892, 'juice': 11261, 'strong': 19815, 'pour': 15767, 'mouth': 13409, 'alive': 1115, 'feeling': 7984, 'feels': 7986, 'through': 20823, 'changes': 3907, 'stronger': 19817, 'names': 13590, 'hey': 9984, 'unless': 21678, 'wish': 22709, 'hit': 10053, 'chug': 4248, 'sensation': 18218, 'must': 13541, 'kitchen': 11505, 'round': 17604, 'powerful': 15784, 'zest': 23123, 'dish': 6412, 'spritz': 19404, 'nearly': 13665, 'outlet': 14520, 'seattle': 18123, 'tacoma': 20308, 'case': 3702, 'tweleve': 21438, 'paying': 14952, '38': 353, 'yes': 22981, 'dollar': 6615, 'either': 7084, 'calorie': 3458, 'whacked': 22505, 'tasty': 20446, 'banana': 2127, 'bread': 3002, 'lowest': 12308, 'town': 21136, 'refreshing': 16869, 'salads': 17740, 'lunch': 12349, 'terrible': 20601, 'breath': 3036, 'sufficiently': 19972, 'resolves': 17218, 'smelly': 18867, 'bacteria': 2067, 'grow': 9475, 'think': 20757, 'part': 14850, 'value': 21904, 'highly': 10011, 'mints': 13127, 'themselves': 20692, 'cheers': 3990, 'tins': 20937, 'mine': 13094, 'perfict': 15124, 'fifty': 8065, 'tin': 20924, 'cary': 3699, 'along': 1164, 'safer': 17724, 'teeth': 20530, 'ones': 14289, 'twelve': 21439, 'dollars': 6618, 'resonable': 17219, 'shareing': 18357, 'mint': 13126, 'youll': 23038, 'carry': 3685, 'pocket': 15545, 'purse': 16338, 'huge': 10279, 'supply': 20084, 'working': 22808, 'plenty': 15512, 'spare': 19211, 'effective': 7045, '11': 52, 'received': 16700, 'shown': 18540, 'mother': 13380, 'law': 11792, 'walgreens': 22267, 'quit': 16456, 'carrying': 3686, 'scent': 17980, 'few': 8042, 'hours': 10237, 'favors': 7946, 'everyone': 7525, 'even': 7499, 'first': 8161, 'tasted': 20428, 'anchovy': 1317, 'stuffed': 19843, 'olive': 14252, 'online': 14295, 'olives': 14256, 'un': 21532, 'subtle': 19927, 'brine': 3091, 'cheeses': 3997, 'appetizer': 1481, 'guests': 9533, 'samovar': 17784, 'herbal': 9946, 'additives': 838, 'blend': 2681, 'destroy': 6092, 'real': 16642, 'pickle': 15306, 'aim': 1030, 'hooked': 10158, 'keep': 11382, 'hand': 9664, 'described': 6043, 'silky': 18614, 'smooth': 18897, 'filling': 8094, 'expiration': 7694, 'date': 5674, 'reccommend': 16689, 'paid': 14691, 'chunk': 4256, 'cash': 3707, 'despite': 6081, 'review': 17328, 'exactly': 7554, 'russian': 17676, 'italian': 11021, 'groceries': 9439, 'ahmad': 1018, 'looseleaf': 12243, 'eith': 7082, 'making': 12505, 'iced': 10406, 'lingering': 12067, 'aftertaste': 964, 'equals': 7384, 'happy': 9714, 'pricey': 15959, 'pick': 15293, 'cant': 3543, 'anywhere': 1438, 'def': 5827, 'daily': 5593, 'basis': 2224, 'gums': 9571, 'healty': 9851, 'between': 2504, 'clean': 4361, 'plack': 15441, 'chops': 4214, 'omaha': 14262, 'steaks': 19579, 'exceptionally': 7587, 'extreme': 7764, 'possibly': 15714, 'frozen': 8666, 'partly': 14867, 'chemical': 4016, 'sensitive': 18229, 'maybe': 12769, 'week': 22434, 'then': 20694, 'boost': 2851, 'energy': 7260, 'hour': 10236, 'depending': 6013, 'how': 10251, 'feel': 7983, 'imo': 10506, 'replace': 17101, 'early': 6946, 'afternoon': 959, 'start': 19540, 'fade': 7804, 'full': 8720, 'workout': 22810, 'guayaki': 9524, 'yerba': 22979, 'mate': 12734, 'teas': 20494, 'compared': 4710, 'toxic': 21138, 'boosters': 2854, 'leave': 11853, 'nasty': 13618, 'chems': 4022, 'behind': 2392, 'body': 2775, 'judge': 11252, 'reacts': 16627, 'differently': 6231, 'muscavado': 13519, 'place': 15435, 'white': 22578, 'advertised': 900, 'savings': 17909, 'half': 9636, 'retail': 17272, 'individual': 10650, 'wise': 22707, 'isn': 11005, 'overly': 14589, 'quite': 16457, 'baking': 2101, 'turn': 21421, 'everyday': 7521, 'service': 18276, 'faster': 7903, 'expected': 7657, 'efficient': 7051, 'seller': 18193, 'thank': 20650, 'addicted': 823, 'far': 7875, 'anymore': 1423, 'say': 17923, 'downhill': 6709, 'chips': 4131, 'occasion': 14138, 'served': 18271, 'twice': 21442, 'wanted': 22304, 'gluten': 9087, 'borderline': 2861, 'diabetic': 6164, 'anyway': 1434, '79': 533, 'ounce': 14498, 'pkg': 15431, 'today': 20983, 'corn': 5107, 'chip': 4124, 'checked': 3968, 'ingredients': 10740, 'name': 13586, 'deceptive': 5777, 'masa': 12693, 'flour': 8314, 'listed': 12100, 'overwhelms': 14624, 'sunchips': 20019, 'husband': 10344, 'said': 17731, 'shots': 18521, 'takes': 20341, 'mornings': 13355, 'drive': 6796, 'otr': 14489, 'road': 17469, 'truck': 21333, 'alert': 1095, 'crash': 5270, 'autoship': 1823, 'seen': 18165, 'unit': 21666, 'compare': 4708, 'put': 16347, 'husbands': 10345, 'stocking': 19677, 'toy': 21143, 'taken': 20340, 'major': 12496, 'cancelled': 3496, 'positive': 15705, 'note': 13938, 'convenience': 5020, 'singles': 18656, 'creamer': 5296, 'require': 17150, 'refrigeration': 16884, 'impossible': 10533, 'wash': 22337, 'cleaned': 4362, 'couldn': 5168, 'life': 11982, 'scrubbing': 18075, 'washed': 22339, 'dishwasher': 6418, 'suggests': 19989, 'themed': 20690, 'wedding': 22425, 'fight': 8068, 'smelled': 18863, 'literally': 12115, 'hide': 9992, 'none': 13878, 'left': 11869, 'tables': 20296, 'espresso': 7432, 'bean': 2288, 'roast': 17476, 'purpose': 16330, 'crunchy': 5436, 'bitter': 2623, 'href': 10259, 'http': 10267, 'www': 22901, 'gp': 9231, 'b00067ad4u': 1915, 'covered': 5213, 'beans': 2290, 'dark': 5654, 'rich': 17371, 'inside': 10799, 'delightful': 5933, 'caffine': 3407, 'zing': 23136, 'missing': 13172, 'india': 10628, 'bars': 2203, 'combo': 4639, 'raisons': 16512, 'choc': 4147, 'thankful': 20652, 'subsrcibe': 19911, 'nantucket': 13598, 'suprised': 20109, 'single': 18655, 'reading': 16633, 'closer': 4433, '24': 240, 'count': 5175, 'green': 9380, 'mountain': 13399, 'weak': 22395, 'tomatoes': 21021, 'star': 19521, 'classic': 4349, 'avocado': 1854, 'sandwich': 17809, 'complex': 4755, 'ketchup': 11426, 'seem': 18159, 'crazy': 5290, 'condiments': 4835, 'overpriced': 14601, 'disgustingly': 6411, 'spiced': 19289, 'marinara': 12629, 'sauce': 17878, 'chain': 3873, 'restaurant': 17248, 'nuts': 14063, 'broken': 3130, 'dirty': 6324, 'cashews': 3710, 'sometimes': 19076, 'another': 1376, 'placed': 15437, 'ham': 9655, 'soup': 19160, 'base': 2211, 'seasoned': 18117, 'greenbeans': 9381, 'msg': 13438, 'realize': 16648, 'return': 17298, 'item': 11032, 'discover': 6390, 'doing': 6607, 'pancakes': 14751, 'fluffy': 8339, 'seltzer': 18198, 'instead': 10828, 'appreciate': 1507, 'thanks': 20655, 'adjustments': 860, 'egg': 7063, 'camping': 3484, 'eggs': 7069, 'ways': 22387, 'however': 10254, 'sent': 18239, 'bag': 2074, 'mess': 12954, 'customer': 5551, 'sevice': 18309, 'care': 3632, 'foolish': 8414, 'ship': 18452, 'poorly': 15640, 'packaged': 14666, 'breaks': 3028, 'easily': 6968, 'spilled': 19308, 'unsealed': 21743, 'tears': 20493, 'packages': 14668, 'light': 11995, 'nutrition': 14056, 'munchies': 13507, 'potato': 15734, 'buisness': 3235, 'till': 20895, 'please': 15495, 'continue': 4988, 'french': 8582, 'web': 22417, 'markets': 12648, 'area': 1554, 'bargain': 2171, 'mccormacks': 12785, 'seasonings': 18119, 'flavorful': 8241, 'cooking': 5067, 'whats': 22515, 'fantastic': 7869, 'improved': 10546, 'offered': 14193, 'bushel': 3312, 'dinosaur': 6299, 'plastic': 15466, 'wrap': 22854, 'cookies': 5066, 'boxes': 2941, 'complaints': 4743, 'absolutely': 666, 'trust': 21349, 'large': 11732, 'dairy': 5596, 'flavored': 8240, 'vinegar': 22110, 'contain': 4958, 'intense': 10859, 'type': 21475, 'kettle': 11429, 'thoroughly': 20791, 'varieties': 21933, 'bbq': 2268, 'hands': 9683, 'market': 12642, 'salty': 17773, 'greasy': 9358, 'crispy': 5363, 'crunch': 5425, 'hint': 10036, 'sweetness': 20226, 'fall': 7838, 'short': 18502, 'wateringly': 22364, '1st': 195, 'personally': 15180, 'yourself': 23046, 'beat': 2300, 'cooked': 5059, 'tangy': 20374, 'crisp': 5352, 'letting': 11933, 'obsolete': 14123, 'school': 18002, 'tastiest': 20440, 'walk': 22268, 'aisle': 1049, 'picking': 15304, 'trademark': 21162, 'blue': 2743, 'putting': 16351, 'clip': 4413, 'eaten': 6980, 'resist': 17207, 'spice': 19288, 'lover': 12289, 'own': 14631, 'risk': 17445, 'stop': 19704, 'father': 7913, 'gift': 8975, 'substantial': 19917, 'bigger': 2541, 'costco': 5147, 'perfectly': 15118, 'why': 22612, 'reason': 16660, 'alaska': 1071, 'grandchildren': 9273, 'rethink': 17286, 'lightly': 12002, 'saved': 17904, 'vinegary': 22113, 'otherwise': 14486, 'spices': 19291, 'suit': 19990, '80': 543, 'cents': 3839, 'let': 11923, 'impressed': 10537, 'commented': 4663, 'yet': 22988, 'may': 12765, 'suprise': 20108, 'll': 12144, 'pepper': 15084, 'watering': 22363, 'crispiness': 5360, 'faint': 7819, 'authentic': 1808, 'backyard': 2062, 'promo': 16109, 'code': 4526, 'ounces': 14499, 'polish': 15586, 'crumbles': 5419, 'overcooked': 14560, 'felt': 7996, 'wiping': 22700, 'fingers': 8130, 'napkin': 13604, 'opening': 14339, 'numerous': 14019, 'flavoring': 8245, 'completely': 4751, 'gross': 9457, 'does': 6584, 'happen': 

In [25]:
print(a.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [27]:
sentences1=df['Summary']

In [30]:
vectorizer=CountVectorizer()
x=vectorizer.fit_transform(sentences1.fillna(""))
vocabulary=vectorizer.vocabulary_

In [32]:
print(vocabulary)

{'good': 3247, 'quality': 6048, 'dog': 2304, 'food': 2962, 'not': 5201, 'as': 485, 'advertised': 213, 'cough': 1797, 'medicine': 4750, 'yay': 8309, 'barley': 636, 'healthy': 3544, 'fresh': 3028, 'and': 380, 'greasy': 3338, 'strawberry': 7175, 'twizzlers': 7786, 'yummy': 8395, 'poor': 5806, 'taste': 7391, 'love': 4497, 'it': 3926, 'home': 3655, 'delivered': 2103, 'twizlers': 7785, 'delicious': 2084, 'product': 5945, 'great': 3339, 'bargain': 630, 'for': 2971, 'the': 7487, 'price': 5912, 'convenience': 1746, 'same': 6480, 'stuff': 7198, 'ass': 494, 'kickin': 4125, 'awesome': 547, 'deal': 2012, 'stale': 7089, 'source': 6965, 'of': 5279, 'electrolytes': 2500, 'preventing': 5910, 'cramps': 1823, 'low': 4506, 'carb': 1218, 'alternative': 325, 'to': 7584, 'gatorade': 3116, 'pretzel': 5906, 'haven': 3517, 'nothing': 5205, 'special': 6999, 'no': 5167, 'tea': 7419, 'flavor': 2901, 'stomach': 7151, 'problems': 5935, 'better': 759, 'life': 4360, 'you': 8346, 'my': 5064, 'who': 8171, 'has': 3506, 'sensitive': 6635, 'mmmmm': 4914, 'so': 6897, 'convenient': 1747, 'loved': 4498, 'these': 7504, 'tartlets': 7387, 'best': 754, 'disappointing': 2237, 'wonderful': 8224, 'perfect': 5619, 'cat': 1271, 'older': 5308, 'cats': 1278, 'holistic': 3650, 'select': 6614, 'spicy': 7018, 'happy': 3482, 'face': 2711, 'nice': 5148, 'snack': 6867, 'licorice': 4354, 'salsa': 6470, 'ehhh': 2485, 'tastes': 7397, 'jell': 3987, 'simple': 6763, 'but': 1100, 'tasteless': 7394, 'calorie': 1151, 'was': 8067, 'back': 574, 'in': 3820, 'day': 2002, 'teen': 7432, 'never': 5134, 'paid': 5462, 'that': 7485, 'much': 5018, 'garbonzo': 3105, 'bean': 674, 'flour': 2929, 'after': 229, 'lunch': 4528, 'altoids': 329, 'mini': 4866, 'mints': 4872, 'tins': 7574, 'tasty': 7409, 'are': 455, 'by': 1118, 'case': 1262, 'looking': 4471, 'different': 2187, 'ever': 2608, 'real': 6126, 'mcclures': 4723, 'bloody': 858, 'mary': 4685, 'mix': 4899, 'this': 7522, 'is': 3916, 'what': 8145, 'get': 3146, 'store': 7163, 'ahmad': 254, 'keeps': 4098, 'out': 5403, 'dentest': 2118, 'chair': 1329, 'pok': 5778, 'chops': 1495, 'energy': 2542, 'shot': 6736, 'me': 4730, 'sugar': 7239, 'raw': 6113, 'excellent': 2639, 'amazing': 342, 'very': 7971, 'chips': 1455, 'over': 5416, 'priced': 5913, 'lack': 4221, 'rice': 6316, 'tested': 7469, 'trucker': 7724, 'quantity': 6049, 'gag': 3089, 'gift': 3164, 'penguin': 5590, 'pooper': 5805, 'arrived': 473, 'coffee': 1609, 'mate': 4703, 'creamer': 1840, 'hazelnut': 3529, 'work': 8239, 'only': 5335, 'ice': 3774, 'beans': 677, 'bar': 621, 'surprise': 7300, 'favorite': 2774, 'really': 6133, 'waste': 8076, 'money': 4962, 'simply': 6766, 'wild': 8185, 'chick': 1422, 'brown': 1027, 'ham': 3459, 'base': 646, 'msg': 5015, 'delisious': 2100, 'pancakes': 5482, 'all': 294, 'around': 470, 'egg': 2477, 'allergic': 298, 'allergy': 300, 'disappointed': 2235, 'shipping': 6707, 'item': 3932, 'packaging': 5451, 'roast': 6358, 'franch': 3002, 'hey': 3598, 'famous': 2731, 'reason': 6134, 'they': 7506, 'thick': 7507, 'crunchy': 1889, 'gluten': 3207, 'free': 3019, 'dairy': 1953, 'buy': 1112, 'bbq': 665, 'yum': 8365, 'make': 4599, 'weak': 8099, 'at': 505, 'knees': 4170, 'pretty': 5904, 'tasting': 7406, 'chip': 1451, 'fantastic': 2739, 'can': 1164, 'beat': 682, 'resist': 6273, 'one': 5330, 'if': 3787, 'spice': 7014, 'lover': 4502, 'an': 372, 'addictive': 193, 'potato': 5845, '70': 106, 'bag': 583, 'cooked': 1758, 'salt': 6471, 'vinegar': 7990, 'unsalted': 7859, 'burnt': 1091, 'completely': 1685, 'ripped': 6343, 'off': 5281, 'fried': 3035, 'kettle': 4117, 'english': 2551, 'sell': 6616, 'awful': 553, 'thing': 7511, 'have': 3516, 'been': 703, 'addicted': 190, 'too': 7620, 'yoli': 8339, 'there': 7501, 'will': 8189, 'fat': 2757, 'caution': 1282, 'tasted': 7392, 'dont': 2325, 'know': 4176, 'smaller': 6831, 'bags': 589, 'ok': 5302, 'miss': 4889, 'vickie': 7979, 'well': 8126, 'balanced': 601, 'earl': 2432, 'grey': 3362, 'your': 8349, 'health': 3538, 'agave': 236, 'syrup': 7340, 'how': 3720, 'could': 1798, 'be': 669, 'had': 3442, 'organic': 5371, 'more': 4982, 'ask': 488, 'from': 3045, 'plocky': 5753, 'sweet': 7319, 'smokey': 6853, 'chipotle': 1453, 'whole': 8173, 'grain': 3294, 'tortill': 7638, 'tortilla': 7639, 'unique': 7843, 'schrumshist': 6558, 'music': 5053, 'palate': 5471, 'kept': 4111, 'secret': 6600, 'fanfreakintastic': 2734, 'smokin': 6855, 'broken': 1019, 'timely': 7567, 'delivery': 2105, 'candy': 1174, 'dum': 2402, 'dums': 2408, 'lots': 4490, 'pops': 5824, 'cuttiest': 1937, 'gum': 3414, 'century': 1312, 'though': 7528, 'kikkoman': 4133, 'than': 7481, 'anything': 421, 'supermarket': 7274, 'sauce': 6525, 'non': 5174, 'gmo': 3215, 'kona': 4180, 'tassimo': 7389, 'wafers': 8020, 'horrible': 3689, 'kleri': 4166, 'works': 8246, 'where': 8158, 'cranberries': 1825, 'edible': 2464, 'speedy': 7006, 'spongetastic': 7035, 'caramel': 1215, 'chocolate': 1470, 'choclate': 1463, 'serious': 6642, '10': 12, 'bucks': 1046, 'quick': 6058, 'arrival': 472, 'basket': 651, 'go': 3223, 'wrong': 8283, 'scottie': 6574, 'royal': 6412, 'canin': 1179, 'cocker': 1593, 'rave': 6109, 'review': 6300, 'rolled': 6382, 'oats': 5259, 'made': 4567, 'uk': 7804, 'or': 5350, 'india': 3842, 'version': 7969, 'breakfast': 971, 'flavorful': 2903, 'purist': 6026, 'black': 827, 'addict': 189, 'soda': 6902, 'melt': 4773, 'pocky': 5767, 'sticks': 7136, 'together': 7600, 'berry': 751, 'size': 6787, 'fan': 2732, 'child': 1433, 'loves': 4504, 'them': 7495, 'highly': 3609, 'recomended': 6166, 'thin': 7510, 'son': 6931, '2nd': 63, 'dish': 2261, 'toss': 7642, '12': 20, 'jars': 3973, 'our': 5401, 'baby': 570, 'dinner': 2210, 'geat': 3120, 'garbanzo': 3104, 'give': 3180, 'gas': 3111, 'liked': 4376, 'moms': 4958, 'dads': 1950, 'beware': 766, 'plastic': 5736, 'allday': 295, 'fruit': 3054, 'sassafras': 6510, 'sassafrass': 6511, 'tasten': 7395, 'expected': 2665, 'white': 8170, 'gravy': 3332, 'pot': 5843, 'diet': 2180, 'with': 8213, 'natural': 5097, 'ingredients': 3866, 'hot': 3700, 'babka': 569, 'she': 6678, 'puppy': 6014, 'dogs': 2311, 'smells': 6840, 'like': 4375, 'roses': 6398, 'safety': 6456, 'freshness': 3032, 'seal': 6588, 'little': 4425, 'warm': 8057, 'cereal': 1314, 'ur': 7881, 'tummy': 7754, 'kellogg': 4102, 'mueslix': 5024, 'yuk': 8364, 'color': 1642, 'exactly': 2631, 'described': 2132, 'cookies': 1761, 'cubes': 1901, 'espresso': 2590, 'melted': 4775, 'gold': 3237, 'plated': 5738, 'reaction': 6119, 'unbelievable': 7823, 'on': 5328, 'hard': 3489, 'find': 2845, 'pruduct': 5976, 'cheap': 1360, 'were': 8131, 'until': 7865, 'people': 5597, 'bought': 926, 'now': 5214, 'meh': 4760, 'reviews': 6304, 'vegetable': 7938, 'lovely': 4501, 'say': 6539, 'blow': 861, 'pop': 5808, 'jolokia': 4025, 'mouth': 5002, 'strong': 7189, 'anus': 416, 'weaker': 8100, 'please': 5746, 'kitty': 4159, 'bland': 837, 'dried': 2374, 'up': 7870, 'just': 4063, 'vendor': 7950, 'their': 7493, 'cultures': 1907, 'other': 5394, 'vendors': 7951, 'dense': 2111, 'bisphenol': 811, 'addicting': 191, 'cute': 1934, 'lollipops': 4460, 'fun': 3073, 'small': 6830, 'swirled': 7330, 'able': 138, 'eat': 2447, 'bread': 967, 'again': 233, 'service': 6647, 'picture': 5677, 'kind': 4138, 'steak': 7119, 'easy': 2445, 'bit': 818, 'overpriced': 5425, 'tho': 7523, 're': 6118, 'single': 6770, 'lifestyle': 4363, 'mashed': 4694, 'taters': 7410, 'omaha': 5321, 'chicken': 1423, 'stuffed': 7199, 'baked': 594, 'potatoies': 5848, 'potatoes': 5847, 'maximum': 4712, 'power': 5866, 'ingredient': 3865, 'list': 4416, 'spray': 7045, 'garlic': 3110, 'detect': 2147, 'prickly': 5917, 'pear': 5565, 'spam': 6986, 'any': 418, 'meal': 4733, 'omg': 5323, 'crab': 1816, 'cakes': 1137, 'delight': 2090, 'healthful': 3540, 'treat': 7691, 'choice': 1483, 'barb': 622, 'vanilla': 7919, 'custard': 1930, 'happily': 3480, 'bird': 802, 'powder': 5863, 'cold': 1625, 'flu': 2935, 'treats': 7693, 'friend': 3036, 'training': 7672, 'em': 2514, 'liver': 4432, 'biscotti': 806, 'jack': 3949, 'crazy': 1837, 'remembered': 6237, 'customer': 1931, 'beer': 705, 'nuts': 5245, 'chocolot': 1476, 'milk': 4848, 'cacao': 1122, 'alive': 292, 'aware': 539, 'mixes': 4902, 'tree': 7694, 'cherry': 1399, 'bites': 821, 'its': 3937, 'darn': 1984, 'tic': 7553, 'tac': 7349, 'easter': 2444, 'bars': 642, 'gf': 3152, 'baking': 598, 'sweets': 7328, 'stevia': 7130, 'oz': 5440, 'pwdr': 6040, 'sweeter': 7323, 'yuck': 8360, 'family': 2730, 'dust': 2418, 'noodle': 5181, 'favorites': 2775, 'noodles': 5182, 'juicy': 4046, 'jays': 3980, 'got': 3269, 'makes': 4602, 'nasty': 5090, 'loose': 4478, 'poo': 5799, 'elsewhere': 2511, 'cutter': 1936, 'fabulous': 2710, 'pasta': 5525, 'thought': 7529, 'exceptional': 2643, 'disgusting': 2259, 'pudding': 5985, 'cook': 1756, 'serve': 6644, 'choc': 1458, 'fudge': 3065, 'also': 322, 'thai': 7479, 'coconut': 1600, 'ginger': 3172, 'soup': 6960, 'okay': 5303, 'pinch': 5696, 'goodness': 3250, 'smell': 6837, 'soooooo': 6942, 'new': 5135, 'cranberry': 1826, 'cup': 1908, 'insane': 3873, 'didn': 2175, 'do': 2297, 'sheds': 6681, 'less': 4334, 'ww': 8288, 'followers': 2957, 'except': 2642, 'pepper': 5604, 'yummies': 8372, 'popchips': 5810, 'crisps': 1859, 'did': 2174, 'care': 1231, 'wondering': 8227, 'why': 8181, 'sellers': 6618, 'quite': 6063, 'interesting': 3895, 'however': 3722, 've': 7930, 'found': 2988, 'something': 6926, 'else': 2510, 'tast': 7390, 'lard': 4247, 'game': 3099, 'wonderfully': 8226, 'short': 6728, 'rock': 6369, 'without': 8215, 'feeling': 2795, 'guilty': 3412, 'variety': 7927, 'those': 7527, 'substitute': 7220, 'hella': 3574, 'absolutely': 145, 'deliciousness': 2086, 'calories': 1152, 'tops': 7632, 'expecting': 2666, 'full': 3072, 'reconsider': 6172, 'getting': 3150, 'another': 400, 'brand': 958, 'cheaper': 1361, 'costco': 1791, 'crunch': 1884, 'solution': 6919, 'receive': 6148, 'ordered': 5359, 'forever': 2974, 'box': 939, 'instead': 3882, 'bad': 581, 'partially': 5513, 'open': 5341, 'basil': 649, 'counter': 1802, 'proof': 5958, 'would': 8259, 'easier': 2441, 'safe': 6453, 'mushy': 5052, 'pineapple': 5698, 'dirty': 2228, 'martini': 4679, 'olive': 5313, 'juice': 4039, 'flecks': 2914, 'morton': 4987, 'sea': 6584, 'ddjj': 2007, 'waffle': 8022, 'pricey': 5915, 'pancake': 5481, 'increased': 3834, 'cost': 1789, 'every': 2611, 'time': 7566, 'waffles': 8023, 'stonewall': 7156, 'kitchen': 4153, 'belgian': 722, 'scrumptious': 6581, 'expensive': 2671, 'crispy': 1860, 'soft': 6906, 'once': 5329, 'mine': 4864, 'versus': 7970, 'don': 2322, 'add': 186, 'unsatisfied': 7860, 'need': 5116, 'figure': 2831, 'kcup': 4089, 'brewers': 996, 'pack': 5446, '35': 73, 'should': 6738, 'crackers': 1821, 'unavailable': 7820, 'penta': 5596, 'com': 1648, 'through': 7539, 'website': 8108, 'wash': 8070, 'record': 6173, 'collection': 1632, 'super': 7268, 'snacks': 6873, 'traveling': 7684, 'throwing': 7542, 'diaper': 2170, 'mishmash': 4882, 'idea': 3782, 'plum': 5756, 'tot': 7643, 'month': 4972, 'old': 5306, 'daughter': 1994, '18month': 40, 'twin': 7775, 'niece': 5153, 'nephew': 5124, 'goji': 3236, 'maca': 4550, 'dozen': 2357, 'stars': 7104, 'grammy': 3299, 'pie': 5680, 'fine': 2848, 'satisfied': 6518, 'recommend': 6167, 'krinos': 4192, 'tahini': 7357, 'cigars': 1514, 'everything': 2615, 'iv': 3940, 'far': 2741, 'false': 2728, 'advertising': 215, 'dop': 2333, 'cento': 1309, 'san': 6488, 'marzano': 4689, 'shows': 6745, 'damaged': 1958, 'merchandise': 4794, 'sure': 7297, 'shame': 6665, 'use': 7889, 'corn': 1775, 'babies': 568, 'conversation': 1749, 'piece': 5681, 'dispenser': 2268, 'cravings': 1833, 'worth': 8254, 'penny': 5594, 'hint': 3624, 'mmmmmmmmmm': 4921, 'top': 7629, 'avoid': 536, 'seloler': 6621, 'below': 732, 'standard': 7092, 'rishi': 6348, 'leaf': 4287, 'marathon': 4648, 'runner': 6430, 'running': 6431, 'recovery': 6175, 'brands': 960, 'tart': 7384, 'concentrate': 1692, 'cherries': 1398, 'skyflakes': 6806, 'classic': 1535, 'jja': 4011, 'comes': 1656, 'high': 3606, 'dough': 2348, 'christmas': 1501, 'canadies': 1167, 'yellow': 8318, 'split': 7029, 'peas': 5570, 'gevalia': 3151, 'melange': 4765, 'maison': 4597, 'corse': 1786, 'pricy': 5918, 'cookie': 1760, 'gettin': 3149, 'down': 2352, 'almost': 309, 'none': 5175, 'caribou': 1235, 'fave': 2767, 'we': 8098, 'bitter': 823, 'mahogany': 4586, 'cups': 1916, 'smooooth': 6860, 'changed': 1342, 'formulation': 2982, '2012': 54, 'refreshing': 6203, 'water': 8083, 'unbalanced': 7821, 'willing': 8190, 'otto': 5396, 'likes': 4378, 'sojos': 6909, 'original': 5381, 'mrs': 5013, 'may': 4715, 'pumpkin': 6006, 'terrific': 7464, 'goody': 3253, 'must': 5055, 'gardener': 3107, 'mustard': 5056, 'ummm': 7811, 'ugh': 7799, 'conflakes': 1708, 'purchase': 6016, 'flaxseed': 2912, 'pkg': 5723, 'says': 6540, 'china': 1447, 'won': 8221, 'carbon': 1221, 'footprint': 2970, 'nut': 5230, 'almond': 306, 'honestly': 3664, 'goes': 3233, 'inside': 3877, 'read': 6121, 'almonds': 307, 'days': 2004, 'lacey': 4219, 'convienent': 1752, 'handy': 3471, 'stash': 7112, 'instant': 3880, 'green': 3352, 'benefits': 737, 'iced': 3775, 'beverage': 763, 'drink': 2375, 'addition': 197, 'lightly': 4370, 'cheeper': 1376, 'jamba': 3963, 'matcha': 4702, 'terrible': 7460, 'mona': 4960, 'lisa': 4414, 'pepsi': 5613, 'popcord': 5811, 'popcorn': 5812, 'lovers': 4503, 'amish': 357, 'country': 1804, 'world': 8247, 'worst': 8253, 'planet': 5729, 'wabash': 8018, 'valley': 7913, 'farms': 2748, 'flies': 2917, 'begone': 717, 'harbor': 3488, 'news': 5142, 'england': 2549, 'clam': 1530, 'chowder': 1497, 'clams': 1532, 'mmmmmm': 4916, 'usa': 7886, 'um': 7809, 'package': 5448, 'change': 1341, '17oz': 35, '16': 31, '9oz': 128, 'vita': 7998, 'coco': 1595, 'unusual': 7868, 'awsome': 554, 'chilled': 1443, 'displayed': 2270, 'order': 5358, 'sugarless': 7242, 'greatest': 3342, 'show': 6741, 'french': 3023, 'oreo': 5367, 'dipped': 2219, 'teaching': 7423, 'yummers': 8368, 'refused': 6210, 'totally': 7645, 'satisfying': 6521, 'seaweed': 6597, 'strange': 7173, 'some': 6923, 'changes': 1343, 'dreams': 2368, 'winter': 8201, 'party': 5518, 'fortune': 2984, 'soooo': 6940, 'tiny': 7575, 'cooking': 1763, 'assembly': 496, 'alpacas': 315, 'truffle': 7729, 'oil': 5297, 'difference': 2186, 'guilt': 3411, 'snacking': 6872, 'grand': 3302, 'orbit': 5354, 'peppermint': 5609, 'chocolates': 1472, 'flax': 2911, 'seed': 6604, 'feel': 2794, 'brownie': 1028, 'brownies': 1029, 'produce': 5942, 'casablanca': 1261, 'toddler': 7593, 'goat': 3224, 'cheese': 1381, 'puroast': 6027, 'acid': 168, 'machine': 4558, 'homemade': 3657, 'spring': 7049, 'amedei': 352, 'bigger': 783, 'amount': 367, 'supermarkets': 7275, 'value': 7916, 'chopped': 1494, 'cocoa': 1596, 'right': 6330, 'along': 313, 'lines': 4398, 'chocoholic': 1466, 'view': 7985, 'grove': 3387, 'square': 7063, 'keurig': 4118, 'artificial': 482, 'sweetner': 7326, 'warms': 8061, 'soul': 6959, 'sucralose': 7232, 'nummy': 5224, 'kids': 4131, 'grandkids': 3307, 'swisshot': 7332, 'pleasantly': 5745, 'surprised': 7301, 'reasonable': 6136, 'listened': 4419, 'funny': 3078, 'city': 1527, 'yet': 8324, 'anyone': 420, 'jz': 4066, 'does': 2301, 'added': 187, 'flavoring': 2905, 'soso': 6955, 'wasn': 8073, 'smooth': 6861, 'olate': 5305, 'cafe': 1128, 'escapes': 2583, 'complain': 1680, 'mmm': 4911, 'thanks': 7483, 'outthere': 5411, 'ages': 239, 'cracker': 1820, 'here': 3588, 'jerky': 3997, 'unsorted': 7861, 'assorted': 498, 'flavored': 2902, 'tacs': 7353, 'pink': 5699, 'grapefruit': 3317, 'deelish': 2055, 'dane': 1968, 'season': 6592, 'mackerels': 4563, 'canned': 1184, 'mackeral': 4561, 'lazzaroni': 4281, 'amarettini': 338, 'graet': 3290, 'pizza': 5720, 'market': 4666, '20': 46, '4oz': 87, 'authentic': 522, 'chinese': 1448, 'dishes': 2262, 'pg': 5650, 'tips': 7577, 'muffins': 5026, 'disappointment': 2238, 'woeber': 8216, 'sandwich': 6493, 'pal': 5469, 'first': 2868, 'word': 8237, 'wants': 8053, 'graham': 3291, 'hands': 3470, 'danes': 1970, 'shedding': 6680, 'dark': 1980, 'muddy': 5023, 'maybe': 4716, 'because': 691, 'date': 1991, 'watery': 8088, 'choloate': 1489, 'doubt': 2347, 'about': 140, 'condiment': 1698, 'curry': 1929, 'geliva': 3125, 'panda': 5484, 'nature': 5100, 'pods': 5769, 'melitta': 4767, 'skip': 6802, 'buzz': 1116, 'norcal': 5187, 'grandma': 3308, 'happened': 3478, 'senseo': 6633, 'decaf': 2025, 'java': 3977, 'users': 7896, 'tried': 7704, 'parisian': 5506, 'blend': 849, 'spices': 7016, 'soy': 6976, 'shortening': 6733, 'sauces': 6527, 'company': 1670, 'yucky': 8362, 'hannah': 3474, 'red': 6177, 'pickled': 5673, 'sausage': 6529, 'gallon': 3096, 'among': 362, 'produced': 5943, 'diabetic': 2166, 'charges': 1353, 'excessive': 2645, 'lot': 4488, 'going': 3235, 'coffees': 1612, 'wow': 8264, 'nutty': 5246, 'cashews': 1266, 'body': 879, 'ms': 5014, 'roxy': 6411, 'contains': 1736, 'fragrance': 2997, 'huge': 3733, 'shower': 6743, 'favor': 2768, 'amazon': 346, 'sells': 6620, 'biscuit': 807, 'crumbs': 1882, 'misleading': 4883, 'ehkkkkkkkkkkkkkkk': 2488, 'combination': 1651, 'skinless': 6798, 'sardines': 6505, 'sodium': 6904, 'actually': 184, 'satisifed': 6522, 'products': 5947, 'diets': 2184, 'available': 531, 'inconsistent': 3828, 'true': 7725, 'plug': 5754, 'play': 5741, 'wherever': 8159, 'theres': 7502, 'pc': 5552, 'decent': 2035, 'enough': 2559, 'gain': 3090, 'monitor': 4966, 'recording': 6174, 'latency': 4259, 'extra': 2693, 'condensor': 1697, 'worked': 8241, 'blue': 866, 'icicle': 3777, 'iffy': 3788, 'thus': 7549, 'keep': 4095, 'stock': 7147, 'shelf': 6684, 'way': 8093, 'bisquick': 813, 'belly': 730, 'cheapest': 1362, 'place': 5725, 'thank': 7482, 'purpose': 6029, 'aid': 257, 'us': 7885, 'lobster': 4445, 'biscuits': 808, 'impressed': 3811, 'snickerdoodles': 6890, 'ahead': 247, 'aluminum': 332, 'grainy': 3296, 'texture': 7476, 'cobbler': 1586, 'gourmet': 3278, 'yummm': 8377, 'yahoo': 8304, 'yummmmm': 8379, 'gram': 3297, 'morning': 4984, 'toothpicks': 7627, 'compared': 1673, 'redbard': 6178, 'bully': 1071, 'stix': 7146, 'felt': 2800, 'thief': 7509, 'when': 8156, 'superb': 7269, 'still': 7139, 'ole': 5311, 'honey': 3665, 'kid': 4127, 'sticky': 7137, 'fingers': 2853, 'foodie': 2963, 'shortbread': 6730, 'hear': 3548, 'chili': 1438, 'chock': 1462, 'amazingness': 345, 'agree': 244, 'others': 5395, 'useable': 7890, 'mellowed': 4770, 'disapointed': 2229, 'robust': 6367, 'wired': 8205, 'night': 5155, 'part': 5512, 'dr': 2358, 'somewhat': 6929, 'cameron': 1156, 'orzo': 5387, 'ener': 2536, 'slightly': 6816, 'allergies': 299, 'received': 6149, 'ultra': 7807, 'wasa': 8068, 'kavli': 4084, 'sooo': 6939, 'sf': 6659, 'above': 141, 'user': 7895, 'golf': 3241, 'set': 6653, 'cake': 1136, 'topper': 7630, 'wilton': 8192, '13': 23, 'gma': 3214, 'pat': 5532, 'dry': 2393, 'worry': 8251, 'shiba': 6693, 'inu': 3902, 'picky': 5676, 'fussy': 3087, 'option': 5348, 'wish': 8208, 'newmans': 5141, 'own': 5432, 'organinc': 5374, 'fooled': 2967, 'organics': 5373, 'name': 5079, 'ethical': 2598, 'premium': 5886, 'adult': 209, 'adjust': 203, 'subscription': 7215, 'newman': 5140, 'formula': 2980, 'needs': 5118, 'seems': 6608, 'enjoy': 2553, 'pet': 5636, 'excellant': 2637, 'wanted': 8051, 'range': 6091, 'reviewer': 6302, 'community': 1668, 'princess': 5921, 'addiction': 192, 'om': 5320, 'nom': 5171, 'toffifay': 7597, 'glad': 3187, 'colombian': 1640, 'mucus': 5020, 'drainage': 2360, 'slow': 6823, 'relief': 6230, 'sinus': 6774, 'pressure': 5902, 'effective': 2474, 'buster': 1098, 'mild': 4844, 'sausages': 6530, 'smokies': 6854, 'beef': 699, 'wine': 8196, 'two': 7787, 'away': 540, 'chardonnay': 1350, 'usual': 7900, 'habla': 3441, 'espanol': 2587, 'cut': 1933, 'offer': 5282, 'ladies': 4228, 'paper': 5491, 'flavia': 2900, 'cinnamon': 1523, 'mentos': 4787, 'tooth': 7626, 'coming': 1660, 'boys': 948, 'seasonings': 6595, 'ground': 3383, 'fennel': 2803, 'mega': 4759, 'bone': 892, 'shopping': 6726, 'skinny': 6800, 'margarita': 4656, 'peanut': 5561, 'brittle': 1014, 'rotton': 6405, 'upon': 7876, 'receipt': 6147, 'longer': 4465, 'hoped': 3678, 'style': 7208, 'truthfull': 7739, 'halal': 3450, 'italian': 3928, 'pamela': 5476, 'think': 7513, 'dulce': 2401, 'de': 2009, 'leche': 4304, 'healthier': 3541, 'most': 4989, 'sugary': 724

In [33]:
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]